# render.yaml - Kostenlose Deployment Konfiguration für VocalIQ
# This file configures all services for Render.com FREE tier

services:
  # Web Service - VocalIQ Backend API
  - type: web
    name: vocaliq-api
    runtime: docker
    repo: https://github.com/MarcelGaertner1234/vocaliq-voice-agent
    plan: free # Kostenloser Plan!
    branch: main
    dockerfilePath: ./Dockerfile.render
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "8000"
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vocaliq-db
          property: connectionString
      # Redis von Upstash (extern)
      - key: REDIS_URL
        sync: false # Manuell in Render Dashboard eingeben
      # API Keys - WICHTIG: Diese in Render Dashboard eingeben!
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true # Automatisch generieren
      - key: ENCRYPTION_KEY
        value: "ToDHON5kuY7-roFy6KRzNxN0HMlnoEKZRs-PkK_oB30=" # CHANGE IN PRODUCTION!
      # CORS für Frontend
      - key: CORS_ORIGINS
        value: '["https://vocaliq-frontend.onrender.com", "http://localhost:5173"]'
      # Twilio (Optional - später hinzufügen)
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false

  # Static Site - VocalIQ Frontend (Automatisch kostenlos!)
  - type: static
    name: vocaliq-frontend
    repo: https://github.com/MarcelGaertner1234/vocaliq-voice-agent
    branch: main
    buildCommand: cd vocaliq-setup-docs/frontend && npm install && npm run build
    staticPublishPath: ./vocaliq-setup-docs/frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# PostgreSQL Database - 90 Tage kostenlos
databases:
  - name: vocaliq-db
    plan: free # Kostenlos für 90 Tage!
    databaseName: vocaliq
    user: vocaliq
    # Nach 90 Tagen: Backup erstellen und neue DB anlegen

# HINWEISE:
# 1. Upstash Redis (extern):
#    - Gehe zu upstash.com
#    - Erstelle kostenlosen Redis
#    - Kopiere Redis URL
#    - Füge in Render Environment ein
#
# 2. Weaviate (optional):
#    - Für Vector Search
#    - Kann später hinzugefügt werden
#    - Oder nutze Supabase pgvector
#
# 3. Nach Deploy:
#    - Frontend URL in CORS_ORIGINS updaten
#    - Custom Domain hinzufügen (optional)
#    - Monitoring einrichten